/** Maschinenlesbare Reason Codes — keine Freitextlogik im Allocator. */
export const REASON = {
	HOUSE_LOAD_REQUIRED: "house_load_required",
	VEHICLE_DEADLINE_REQUIRED: "vehicle_deadline_required",
	VEHICLE_PRESENCE_REQUIRED: "vehicle_presence_required",
	PV_SURPLUS_AVAILABLE: "pv_surplus_available",
	PV_EXPECTED_BEFORE_DEADLINE: "pv_expected_before_deadline",
	THERMAL_FLEX_AVAILABLE: "thermal_flex_available",
	THERMAL_DEADLINE_PV_WINDOW: "thermal_deadline_pv_window",
	THERMAL_EMPTY_AT_ESTIMATED: "thermal_empty_at_estimated",
	BATTERY_SOC_TARGET: "battery_soc_target",
	BATTERY_RESERVE_PROTECTED: "battery_reserve_protected",
	BATTERY_NIGHT_RESERVE: "battery_night_reserve",
	BATTERY_CHARGE_DEADLINE: "battery_charge_deadline",
	BATTERY_DISCHARGE_LIVE_UNSUPPORTED: "battery_discharge_live_unsupported",
	/** Passive Battery-Energiequelle gesperrt (Manual/Hold/Ownership/unknown Mode). */
	BATTERY_PASSIVE_ENERGY_UNAVAILABLE: "battery_passive_energy_unavailable",
	/** Plan: kWh oberhalb des zeitabhängigen Reserve-Floors für Flex-Verbraucher nutzbar. */
	BATTERY_FLEX_USABLE: "battery_flex_usable",
	BATTERY_FROM_RESERVE_FLEX: "battery_from_reserve_flex",
	GRID_IMPORT_COST_OPTIMAL: "grid_import_cost_optimal",
	GRID_IMPORT_CONSERVATIVE_DEADLINE: "grid_import_conservative_deadline",
	EXPORT_UNAVOIDABLE: "export_unavoidable",
	CLIMATE_FLEX: "climate_flex",
	OTHER_FLEX: "other_flex",
	MIN_POWER_SLOT: "min_power_slot",
	PV_FORECAST_DEGRADED: "pv_forecast_degraded",
	HOUSE_LOAD_DEGRADED: "house_load_degraded",
	EXPORT_TARIFF_UNKNOWN: "export_tariff_unknown",
	VEHICLE_PRESENCE_UNKNOWN: "vehicle_presence_unknown",
	VEHICLE_AVAILABLE_NOW: "vehicle_available_now",
	VEHICLE_UNAVAILABLE_NOW: "vehicle_unavailable_now",
	VEHICLE_PRESENCE_PREDICTED_AVAILABLE: "vehicle_presence_predicted_available",
	VEHICLE_PRESENCE_PREDICTED_UNAVAILABLE: "vehicle_presence_predicted_unavailable",
	VEHICLE_PRESENCE_EXPLICIT: "vehicle_presence_explicit",
	VEHICLE_GOAL_REACHABLE: "vehicle_goal_reachable",
	VEHICLE_GOAL_AT_RISK: "vehicle_goal_at_risk",
	VEHICLE_GOAL_UNREACHABLE: "vehicle_goal_unreachable",
	VEHICLE_GOAL_AT_RISK_DUE_TO_UNKNOWN_AVAILABILITY:
		"vehicle_goal_at_risk_due_to_unknown_availability",
	VEHICLE_IMPORT_WINDOW_AVAILABLE: "vehicle_import_window_available",
	VEHICLE_PV_WINDOW_AVAILABLE: "vehicle_pv_window_available",
	BATTERY_TELEMETRY_MISSING: "battery_telemetry_missing",
	REPLAN_DAY_ROLLOVER: "replan_day_rollover",
	REPLAN_VEHICLE_PRESENCE_CHANGED: "replan_vehicle_presence_changed",
	REPLAN_PV_FORECAST_CHANGED: "replan_pv_forecast_changed",
	REPLAN_PV_ACTUAL_DEVIATION: "replan_pv_actual_deviation",
	REPLAN_HOUSE_LOAD_DEVIATION: "replan_house_load_deviation",
	REPLAN_BATTERY_SOC_DEVIATION: "replan_battery_soc_deviation",
	REPLAN_THERMAL_DEVIATION: "replan_thermal_deviation",
	REPLAN_AC_COMFORT_CHANGE: "replan_ac_comfort_change",
	REPLAN_VEHICLE_CONNECTED: "replan_vehicle_connected",
	REPLAN_VEHICLE_DISCONNECTED: "replan_vehicle_disconnected",
	REPLAN_VEHICLE_GOAL_CHANGED: "replan_vehicle_goal_changed",
	REPLAN_PRICE_REVISION: "replan_price_revision",
	/** Add-on execution mode off|dryrun|live geändert — frische Participation/Allocation. */
	REPLAN_ADDON_EXECUTION_MODE: "replan_addon_execution_mode",
} as const;

export type UnifiedReasonCode = (typeof REASON)[keyof typeof REASON];
