export const WALLBOX_RUNTIME_BASE = "addons.wallbox.runtime";

export const WALLBOX_RUNTIME_STATES = {
	decisionSource: `${WALLBOX_RUNTIME_BASE}.decision_source`,
	reasonDe: `${WALLBOX_RUNTIME_BASE}.reason_de`,
	dailyPlanStatus: `${WALLBOX_RUNTIME_BASE}.daily_plan_status`,
	dailyPlanValid: `${WALLBOX_RUNTIME_BASE}.daily_plan_valid`,
	dailyPlanRevision: `${WALLBOX_RUNTIME_BASE}.daily_plan_revision`,
	dailyPlanSlotStart: `${WALLBOX_RUNTIME_BASE}.daily_plan_slot_start`,
	dailyPlanSlotEnd: `${WALLBOX_RUNTIME_BASE}.daily_plan_slot_end`,
	connected: `${WALLBOX_RUNTIME_BASE}.connected`,
	chargingAllowedByPlan: `${WALLBOX_RUNTIME_BASE}.charging_allowed_by_plan`,
	allocatedPowerW: `${WALLBOX_RUNTIME_BASE}.allocated_power_w`,
	allocatedEnergyKwh: `${WALLBOX_RUNTIME_BASE}.allocated_energy_kwh`,
	allocatedPvPowerW: `${WALLBOX_RUNTIME_BASE}.allocated_pv_power_w`,
	allocatedGridPowerW: `${WALLBOX_RUNTIME_BASE}.allocated_grid_power_w`,
	energySource: `${WALLBOX_RUNTIME_BASE}.energy_source`,
	deadlineIso: `${WALLBOX_RUNTIME_BASE}.deadline_iso`,
	remainingEnergyKwh: `${WALLBOX_RUNTIME_BASE}.remaining_energy_kwh`,
	plannedEnergyUntilDeadlineKwh: `${WALLBOX_RUNTIME_BASE}.planned_energy_until_deadline_kwh`,
	plannedPvEnergyUntilDeadlineKwh: `${WALLBOX_RUNTIME_BASE}.planned_pv_energy_until_deadline_kwh`,
	plannedGridEnergyUntilDeadlineKwh: `${WALLBOX_RUNTIME_BASE}.planned_grid_energy_until_deadline_kwh`,
	plannedCostUntilDeadlineCt: `${WALLBOX_RUNTIME_BASE}.planned_cost_until_deadline_ct`,
	deadlineReachable: `${WALLBOX_RUNTIME_BASE}.deadline_reachable`,
	firstPlannedSlot: `${WALLBOX_RUNTIME_BASE}.first_planned_slot`,
	lastPlannedSlot: `${WALLBOX_RUNTIME_BASE}.last_planned_slot`,
	activePlannedSlots: `${WALLBOX_RUNTIME_BASE}.active_planned_slots`,
	maxPlannedPowerW: `${WALLBOX_RUNTIME_BASE}.max_planned_power_w`,
	minChargePowerW: `${WALLBOX_RUNTIME_BASE}.min_charge_power_w`,
	maxChargePowerW: `${WALLBOX_RUNTIME_BASE}.max_charge_power_w`,
	planExecutionStatus: `${WALLBOX_RUNTIME_BASE}.plan_execution_status`,
	externalPlanActive: `${WALLBOX_RUNTIME_BASE}.external_plan_active`,
	externalPlanTime: `${WALLBOX_RUNTIME_BASE}.external_plan_time`,
	governanceAllowed: `${WALLBOX_RUNTIME_BASE}.governance_allowed`,
	runtimeControlAvailable: `${WALLBOX_RUNTIME_BASE}.runtime_control_available`,
	writeAllowed: `${WALLBOX_RUNTIME_BASE}.write_allowed`,
} as const;
