export const WALLBOX_RUNTIME_BASE = "addons.wallbox.runtime";

/**
 * Lean surface: Betrieb + sinnvolle Diagnose als Einzelstates.
 * Tiefe Write/Feedback-Contracts → {@link WALLBOX_RUNTIME_STATES.detailJson} + Support-Paket.
 */
export const WALLBOX_RUNTIME_STATES = {
	decisionSource: `${WALLBOX_RUNTIME_BASE}.decision_source`,
	reasonDe: `${WALLBOX_RUNTIME_BASE}.reason_de`,
	dailyPlanStatus: `${WALLBOX_RUNTIME_BASE}.daily_plan_status`,
	dailyPlanValid: `${WALLBOX_RUNTIME_BASE}.daily_plan_valid`,
	dailyPlanRevision: `${WALLBOX_RUNTIME_BASE}.daily_plan_revision`,
	dailyPlanSlotStart: `${WALLBOX_RUNTIME_BASE}.daily_plan_slot_start`,
	dailyPlanSlotEnd: `${WALLBOX_RUNTIME_BASE}.daily_plan_slot_end`,
	connected: `${WALLBOX_RUNTIME_BASE}.connected`,
	chargingAllowedByPlan: `${WALLBOX_RUNTIME_BASE}.charging_allowed_by_plan`,
	allocatedPowerW: `${WALLBOX_RUNTIME_BASE}.allocated_power_w`,
	allocatedEnergyKwh: `${WALLBOX_RUNTIME_BASE}.allocated_energy_kwh`,
	allocatedPvPowerW: `${WALLBOX_RUNTIME_BASE}.allocated_pv_power_w`,
	allocatedGridPowerW: `${WALLBOX_RUNTIME_BASE}.allocated_grid_power_w`,
	energySource: `${WALLBOX_RUNTIME_BASE}.energy_source`,
	deadlineIso: `${WALLBOX_RUNTIME_BASE}.deadline_iso`,
	remainingEnergyKwh: `${WALLBOX_RUNTIME_BASE}.remaining_energy_kwh`,
	plannedEnergyUntilDeadlineKwh: `${WALLBOX_RUNTIME_BASE}.planned_energy_until_deadline_kwh`,
	plannedPvEnergyUntilDeadlineKwh: `${WALLBOX_RUNTIME_BASE}.planned_pv_energy_until_deadline_kwh`,
	plannedGridEnergyUntilDeadlineKwh: `${WALLBOX_RUNTIME_BASE}.planned_grid_energy_until_deadline_kwh`,
	plannedCostUntilDeadlineCt: `${WALLBOX_RUNTIME_BASE}.planned_cost_until_deadline_ct`,
	deadlineReachable: `${WALLBOX_RUNTIME_BASE}.deadline_reachable`,
	firstPlannedSlot: `${WALLBOX_RUNTIME_BASE}.first_planned_slot`,
	lastPlannedSlot: `${WALLBOX_RUNTIME_BASE}.last_planned_slot`,
	activePlannedSlots: `${WALLBOX_RUNTIME_BASE}.active_planned_slots`,
	maxPlannedPowerW: `${WALLBOX_RUNTIME_BASE}.max_planned_power_w`,
	minChargePowerW: `${WALLBOX_RUNTIME_BASE}.min_charge_power_w`,
	maxChargePowerW: `${WALLBOX_RUNTIME_BASE}.max_charge_power_w`,
	planExecutionStatus: `${WALLBOX_RUNTIME_BASE}.plan_execution_status`,
	externalPlanActive: `${WALLBOX_RUNTIME_BASE}.external_plan_active`,
	externalPlanTime: `${WALLBOX_RUNTIME_BASE}.external_plan_time`,
	governanceAllowed: `${WALLBOX_RUNTIME_BASE}.governance_allowed`,
	runtimeControlAvailable: `${WALLBOX_RUNTIME_BASE}.runtime_control_available`,
	writeAllowed: `${WALLBOX_RUNTIME_BASE}.write_allowed`,
	writeLiveEligible: `${WALLBOX_RUNTIME_BASE}.write_live_eligible`,
	dispatchStatus: `${WALLBOX_RUNTIME_BASE}.dispatch_status`,
	dispatchReasonDe: `${WALLBOX_RUNTIME_BASE}.dispatch_reason_de`,
	dispatchAction: `${WALLBOX_RUNTIME_BASE}.dispatch_action`,
	dispatchSource: `${WALLBOX_RUNTIME_BASE}.dispatch_source`,
	dispatchValidUntil: `${WALLBOX_RUNTIME_BASE}.dispatch_valid_until`,
	dispatchDailyPlanRevision: `${WALLBOX_RUNTIME_BASE}.dispatch_daily_plan_revision`,
	targetEnabled: `${WALLBOX_RUNTIME_BASE}.target_enabled`,
	targetPowerW: `${WALLBOX_RUNTIME_BASE}.target_power_w`,
	targetCurrentA: `${WALLBOX_RUNTIME_BASE}.target_current_a`,
	targetPhases: `${WALLBOX_RUNTIME_BASE}.target_phases`,
	targetEvccMode: `${WALLBOX_RUNTIME_BASE}.target_evcc_mode`,
	deadlineStatus: `${WALLBOX_RUNTIME_BASE}.deadline_status`,
	deadlineRisk: `${WALLBOX_RUNTIME_BASE}.deadline_risk`,
	controlMappingComplete: `${WALLBOX_RUNTIME_BASE}.control_mapping_complete`,
	controlMappingMissingJson: `${WALLBOX_RUNTIME_BASE}.control_mapping_missing_json`,
	executionAttempted: `${WALLBOX_RUNTIME_BASE}.execution_attempted`,
	executionExecuted: `${WALLBOX_RUNTIME_BASE}.execution_executed`,
	executionBlockReason: `${WALLBOX_RUNTIME_BASE}.execution_block_reason`,
	writeContractBlockReason: `${WALLBOX_RUNTIME_BASE}.write_contract_block_reason`,
	feedbackStatus: `${WALLBOX_RUNTIME_BASE}.feedback_status`,
	feedbackBlockReason: `${WALLBOX_RUNTIME_BASE}.feedback_block_reason`,
	activeVehicleId: `${WALLBOX_RUNTIME_BASE}.active_vehicle_id`,
	activeVehicleName: `${WALLBOX_RUNTIME_BASE}.active_vehicle_name`,
	activeVehicleSource: `${WALLBOX_RUNTIME_BASE}.active_vehicle_source`,
	activeVehicleDetectionStatus: `${WALLBOX_RUNTIME_BASE}.active_vehicle_detection_status`,
	activeVehicleConfidence: `${WALLBOX_RUNTIME_BASE}.active_vehicle_confidence`,
	activeVehicleProfileValid: `${WALLBOX_RUNTIME_BASE}.active_vehicle_profile_valid`,
	activeVehiclePlanningCapability: `${WALLBOX_RUNTIME_BASE}.active_vehicle_planning_capability`,
	vehicleProfileCount: `${WALLBOX_RUNTIME_BASE}.vehicle_profile_count`,
	vehicleEnabledProfileCount: `${WALLBOX_RUNTIME_BASE}.vehicle_enabled_profile_count`,
	vehicleResolutionReason: `${WALLBOX_RUNTIME_BASE}.vehicle_resolution_reason`,
	vehicleProfileResolved: `${WALLBOX_RUNTIME_BASE}.vehicle_profile_resolved`,
	vehicleActiveForCharging: `${WALLBOX_RUNTIME_BASE}.vehicle_active_for_charging`,
	vehicleConnected: `${WALLBOX_RUNTIME_BASE}.vehicle_connected`,
	activeVehicleResolvedSocPct: `${WALLBOX_RUNTIME_BASE}.active_vehicle_resolved_soc_pct`,
	activeVehicleResolvedSocSource: `${WALLBOX_RUNTIME_BASE}.active_vehicle_resolved_soc_source`,
	activeVehicleResolvedSocQuality: `${WALLBOX_RUNTIME_BASE}.active_vehicle_resolved_soc_quality`,
	activeVehicleCurrentBatteryEnergyKwh: `${WALLBOX_RUNTIME_BASE}.active_vehicle_current_battery_energy_kwh`,
	activeVehicleRequiredBatteryEnergyKwh: `${WALLBOX_RUNTIME_BASE}.active_vehicle_required_battery_energy_kwh`,
	activeVehicleSocEnergyReady: `${WALLBOX_RUNTIME_BASE}.active_vehicle_soc_energy_ready`,
	activeVehicleSocEnergyReasonCode: `${WALLBOX_RUNTIME_BASE}.active_vehicle_soc_energy_reason_code`,
	/** Deep write/feedback/dispatch detail for Support-Diagnose (not individual leaves). */
	detailJson: `${WALLBOX_RUNTIME_BASE}.detail_json`,
} as const;

/** Legacy ballast leaves — purged by surface cleanup, no longer ensured. */
export const WALLBOX_RUNTIME_BALLAST_SUFFIXES = [
	"dispatch_intent_json",
	"dispatch_target_json",
	"dryrun_command_json",
	"command_candidate_json",
	"command_candidate_present",
	"live_foundation_phase",
	"live_write_released",
	"write_plan_present",
	"write_plan_json",
	"write_contract_ready",
	"feedback_contract_ready",
	"write_operation_count",
	"write_control_model",
	"write_evcc_path_confirmed",
	"write_scenario",
	"write_control_path_reason",
	"legacy_mappings_present",
	"evcc_control_mappings_present",
	"control_mapping_diagnostics_json",
	"feedback_contract_present",
	"feedback_contract_json",
	"feedback_required",
	"feedback_contract_structural_ready",
	"feedback_issue_kind",
	"feedback_expectation_count",
	"feedback_matched_count",
	"feedback_mismatch_count",
	"feedback_unavailable_count",
	"feedback_invalid_count",
	"feedback_settle_time_ms",
	"feedback_timeout_ms",
	"active_vehicle_snapshot_json",
] as const;
