import { addonStatusBase } from "../../../tree_paths";
import type { StateHost } from "../../../ems_light/state_util";
import { ensureChannel, ensureStates, type StateDef } from "../../../ems_light/state_util";

const EV_FOUNDATION_BASE = `${addonStatusBase("wallbox")}.ev_foundation`;

export const WALLBOX_EV_FOUNDATION_STATES = {
	evccReachable: `${EV_FOUNDATION_BASE}.evcc_reachable`,
	vehicleConnected: `${EV_FOUNDATION_BASE}.vehicle_connected`,
	charging: `${EV_FOUNDATION_BASE}.charging`,
	chargePowerW: `${EV_FOUNDATION_BASE}.charge_power_w`,
	evccMode: `${EV_FOUNDATION_BASE}.evcc_mode`,
	phasesConfigured: `${EV_FOUNDATION_BASE}.phases_configured`,
	phasesActive: `${EV_FOUNDATION_BASE}.phases_active`,
	vehicleSocPct: `${EV_FOUNDATION_BASE}.vehicle_soc_pct`,
	vehicleSocQuality: `${EV_FOUNDATION_BASE}.vehicle_soc_quality`,
	capabilitiesJson: `${EV_FOUNDATION_BASE}.capabilities_json`,
	externalControlActive: `${EV_FOUNDATION_BASE}.external_control_active`,
	externalControlType: `${EV_FOUNDATION_BASE}.external_control_type`,
	externalControlConfigured: `${EV_FOUNDATION_BASE}.external_control_configured`,
	gridRewardsActive: `${EV_FOUNDATION_BASE}.grid_rewards_active`,
	smartChargingActive: `${EV_FOUNDATION_BASE}.smart_charging_active`,
	externalSourceQuality: `${EV_FOUNDATION_BASE}.external_source_quality`,
	externalSourceUpdatedAt: `${EV_FOUNDATION_BASE}.external_source_updated_at`,
	externalSmartPlanMappingConfigured: `${EV_FOUNDATION_BASE}.external_smart_plan_mapping_configured`,
	externalSmartPlanParseable: `${EV_FOUNDATION_BASE}.external_smart_plan_parseable`,
	externalSmartPlanAvailable: `${EV_FOUNDATION_BASE}.external_smart_plan_available`,
	externalSmartPlanSlotCount: `${EV_FOUNDATION_BASE}.external_smart_plan_slot_count`,
	externalSmartPlanNextStart: `${EV_FOUNDATION_BASE}.external_smart_plan_next_start`,
	externalSmartPlanLastEnd: `${EV_FOUNDATION_BASE}.external_smart_plan_last_end`,
	externalPlanRemainingEnergyKwh: `${EV_FOUNDATION_BASE}.external_plan_remaining_energy_kwh`,
	externalPlanRemainingMinutes: `${EV_FOUNDATION_BASE}.external_plan_remaining_minutes`,
	externalPlanDeadlineUsed: `${EV_FOUNDATION_BASE}.external_plan_deadline_used`,
	externalSmartPlanJson: `${EV_FOUNDATION_BASE}.external_smart_plan_json`,
	externalRawDiagnosticsJson: `${EV_FOUNDATION_BASE}.external_raw_diagnostics_json`,
	departureMinSocConfigured: `${EV_FOUNDATION_BASE}.departure_min_soc_configured`,
	externalMinSocPct: `${EV_FOUNDATION_BASE}.external_min_soc_pct`,
	externalMinSocQuality: `${EV_FOUNDATION_BASE}.external_min_soc_quality`,
	vehicleModelSource: `${EV_FOUNDATION_BASE}.vehicle_model_source`,
	vehicleModelReady: `${EV_FOUNDATION_BASE}.vehicle_model_ready`,
	controlContractModel: `${EV_FOUNDATION_BASE}.control_contract_model`,
	evccControlContractReady: `${EV_FOUNDATION_BASE}.evcc_control_contract_ready`,
	legacyDirectControlPresent: `${EV_FOUNDATION_BASE}.legacy_direct_control_present`,
	evccModeControlVariant: `${EV_FOUNDATION_BASE}.evcc_mode_control_variant`,
	evccModeFeedbackState: `${EV_FOUNDATION_BASE}.evcc_mode_feedback_state`,
	evccModeButtonsReady: `${EV_FOUNDATION_BASE}.evcc_mode_buttons_ready`,
	evccModeOffTargetReady: `${EV_FOUNDATION_BASE}.evcc_mode_off_target_ready`,
	evccModePvTargetReady: `${EV_FOUNDATION_BASE}.evcc_mode_pv_target_ready`,
	evccModeMinTargetReady: `${EV_FOUNDATION_BASE}.evcc_mode_min_target_ready`,
	evccModeNowTargetReady: `${EV_FOUNDATION_BASE}.evcc_mode_now_target_ready`,
	preparedEvState: `${EV_FOUNDATION_BASE}.prepared_ev_state`,
	takeoverReason: `${EV_FOUNDATION_BASE}.takeover_reason`,
	externalAuthorityState: `${EV_FOUNDATION_BASE}.external_authority_state`,
	energyToTargetKwh: `${EV_FOUNDATION_BASE}.energy_to_target_kwh`,
	energyToDepartureMinimumKwh: `${EV_FOUNDATION_BASE}.energy_to_departure_minimum_kwh`,
	requiredChargingMinutes: `${EV_FOUNDATION_BASE}.required_charging_minutes`,
	latestRequiredStart: `${EV_FOUNDATION_BASE}.latest_required_start`,
	deadlineRisk: `${EV_FOUNDATION_BASE}.deadline_risk`,
	externalPlanExpectedSocGainPct: `${EV_FOUNDATION_BASE}.external_plan_expected_soc_gain_pct`,
	externalPlanExpectedFinalSocPct: `${EV_FOUNDATION_BASE}.external_plan_expected_final_soc_pct`,
	externalPlanCoversTarget: `${EV_FOUNDATION_BASE}.external_plan_covers_target`,
	externalPlanCoversDepartureMinimum: `${EV_FOUNDATION_BASE}.external_plan_covers_departure_minimum`,
	remainingFeasibleEnergyKwh: `${EV_FOUNDATION_BASE}.remaining_feasible_energy_kwh`,
	remainingCheapEnergyKwh: `${EV_FOUNDATION_BASE}.remaining_cheap_energy_kwh`,
	economicWindowLossRisk: `${EV_FOUNDATION_BASE}.economic_window_loss_risk`,
	takeoverRecommended: `${EV_FOUNDATION_BASE}.takeover_recommended`,
	takeoverRequired: `${EV_FOUNDATION_BASE}.takeover_required`,
	takeoverSeverity: `${EV_FOUNDATION_BASE}.takeover_severity`,
	recommendedEvState: `${EV_FOUNDATION_BASE}.recommended_ev_state`,
	takeoverDecisionJson: `${EV_FOUNDATION_BASE}.takeover_decision_json`,
	dataQuality: `${EV_FOUNDATION_BASE}.data_quality`,
	modelJson: `${EV_FOUNDATION_BASE}.model_json`,
	updatedAt: `${EV_FOUNDATION_BASE}.updated_at`,
	evPlannerParticipating: `${EV_FOUNDATION_BASE}.ev_planner_participating`,
	evPlannerRole: `${EV_FOUNDATION_BASE}.ev_planner_role`,
	evManagementMode: `${EV_FOUNDATION_BASE}.ev_management_mode`,
	evHardEnergyKwh: `${EV_FOUNDATION_BASE}.ev_hard_energy_kwh`,
	evTargetEnergyKwh: `${EV_FOUNDATION_BASE}.ev_target_energy_kwh`,
	evAcEnergyRequiredKwh: `${EV_FOUNDATION_BASE}.ev_ac_energy_required_kwh`,
	evPlannedEnergyKwh: `${EV_FOUNDATION_BASE}.ev_planned_energy_kwh`,
	evUnplannedEnergyKwh: `${EV_FOUNDATION_BASE}.ev_unplanned_energy_kwh`,
	evPlannedCostEur: `${EV_FOUNDATION_BASE}.ev_planned_cost_eur`,
	evPlannedPvEnergyKwh: `${EV_FOUNDATION_BASE}.ev_planned_pv_energy_kwh`,
	evPlannedGridEnergyKwh: `${EV_FOUNDATION_BASE}.ev_planned_grid_energy_kwh`,
	evPlannedFirstStart: `${EV_FOUNDATION_BASE}.ev_planned_first_start`,
	evPlannedLastEnd: `${EV_FOUNDATION_BASE}.ev_planned_last_end`,
	evPlanQuality: `${EV_FOUNDATION_BASE}.ev_plan_quality`,
	evPlanJson: `${EV_FOUNDATION_BASE}.ev_plan_json`,
	evExecutionEnabled: `${EV_FOUNDATION_BASE}.ev_execution_enabled`,
	evExecutionAuthority: `${EV_FOUNDATION_BASE}.ev_execution_authority`,
	evExecutionReady: `${EV_FOUNDATION_BASE}.ev_execution_ready`,
	evExecutionBlockReason: `${EV_FOUNDATION_BASE}.ev_execution_block_reason`,
	evExecutionDesiredMode: `${EV_FOUNDATION_BASE}.ev_execution_desired_mode`,
	evExecutionDesiredReason: `${EV_FOUNDATION_BASE}.ev_execution_desired_reason`,
	evExecutionActualMode: `${EV_FOUNDATION_BASE}.ev_execution_actual_mode`,
	evExecutionSourceFresh: `${EV_FOUNDATION_BASE}.ev_execution_source_fresh`,
	evExecutionOwnership: `${EV_FOUNDATION_BASE}.ev_execution_ownership`,
	evExecutionOwnedMode: `${EV_FOUNDATION_BASE}.ev_execution_owned_mode`,
	evExecutionOwnedSince: `${EV_FOUNDATION_BASE}.ev_execution_owned_since`,
	evExecutionReleaseReason: `${EV_FOUNDATION_BASE}.ev_execution_release_reason`,
	evExecutionPendingMode: `${EV_FOUNDATION_BASE}.ev_execution_pending_mode`,
	evExecutionPendingSince: `${EV_FOUNDATION_BASE}.ev_execution_pending_since`,
	evExecutionLastCommand: `${EV_FOUNDATION_BASE}.ev_execution_last_command`,
	evExecutionLastCommandAt: `${EV_FOUNDATION_BASE}.ev_execution_last_command_at`,
	evExecutionLastFeedbackAt: `${EV_FOUNDATION_BASE}.ev_execution_last_feedback_at`,
	evExecutionRetryCount: `${EV_FOUNDATION_BASE}.ev_execution_retry_count`,
	evExecutionLastResult: `${EV_FOUNDATION_BASE}.ev_execution_last_result`,
	evExecutionFailsafeReason: `${EV_FOUNDATION_BASE}.ev_execution_failsafe_reason`,
	evExecutionPhase: `${EV_FOUNDATION_BASE}.ev_execution_phase`,
	evExecutionExplain: `${EV_FOUNDATION_BASE}.ev_execution_explain`,
	evExecutionLiveTestArmed: `${EV_FOUNDATION_BASE}.ev_execution_live_test_armed`,
	evExecutionLiveTestDisarm: `${EV_FOUNDATION_BASE}.ev_execution_live_test_disarm`,
	evExecutionLiveTestConsumed: `${EV_FOUNDATION_BASE}.ev_execution_live_test_consumed`,
	evExecutionLiveTestArmedAt: `${EV_FOUNDATION_BASE}.ev_execution_live_test_armed_at`,
	evExecutionLiveTestConsumedAt: `${EV_FOUNDATION_BASE}.ev_execution_live_test_consumed_at`,
	evExecutionLiveTestCommand: `${EV_FOUNDATION_BASE}.ev_execution_live_test_command`,
	evExecutionLiveTestResult: `${EV_FOUNDATION_BASE}.ev_execution_live_test_result`,
	evExecutionLiveTestBlockReason: `${EV_FOUNDATION_BASE}.ev_execution_live_test_block_reason`,
} as const;

/** Öffentliche EV-Foundation: Authority, Smart-Plan-Inputs, kompakte Execution, Live-Test. */
export const WALLBOX_EV_FOUNDATION_PUBLIC_STATE_IDS = new Set<string>([
	WALLBOX_EV_FOUNDATION_STATES.externalSmartPlanJson,
	WALLBOX_EV_FOUNDATION_STATES.externalMinSocPct,
	WALLBOX_EV_FOUNDATION_STATES.externalAuthorityState,
	WALLBOX_EV_FOUNDATION_STATES.takeoverSeverity,
	WALLBOX_EV_FOUNDATION_STATES.preparedEvState,
	WALLBOX_EV_FOUNDATION_STATES.evExecutionEnabled,
	WALLBOX_EV_FOUNDATION_STATES.evExecutionAuthority,
	WALLBOX_EV_FOUNDATION_STATES.evExecutionReady,
	WALLBOX_EV_FOUNDATION_STATES.evExecutionBlockReason,
	WALLBOX_EV_FOUNDATION_STATES.evExecutionDesiredMode,
	WALLBOX_EV_FOUNDATION_STATES.evExecutionExplain,
	WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestArmed,
	WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestDisarm,
	WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestConsumed,
	WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestResult,
	WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestBlockReason,
]);

export const WALLBOX_EV_FOUNDATION_BALLAST_SUFFIXES = Object.values(WALLBOX_EV_FOUNDATION_STATES)
	.filter((id) => !WALLBOX_EV_FOUNDATION_PUBLIC_STATE_IDS.has(id))
	.map((id) => id.slice(EV_FOUNDATION_BASE.length + 1));

function boolState(id: string, name: string, write = false, role = "state"): StateDef {
	return {
		id,
		common: { name, type: "boolean", role, read: true, write, def: false },
	};
}

function numState(id: string, name: string, unit?: string): StateDef {
	return {
		id,
		common: {
			name,
			type: "number",
			role: unit === "W" ? "value.power" : "value",
			unit,
			read: true,
			write: false,
		},
	};
}

function strState(id: string, name: string, role = "text"): StateDef {
	return {
		id,
		common: { name, type: "string", role, read: true, write: false },
	};
}

export async function ensureWallboxEvFoundationStates(host: StateHost): Promise<void> {
	await ensureChannel(host, EV_FOUNDATION_BASE, "EV-Fundament (Diagnose)");
	await ensureStates(host, [
		boolState(WALLBOX_EV_FOUNDATION_STATES.evccReachable, "EVCC erreichbar"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.vehicleConnected, "Fahrzeug verbunden"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.charging, "Fahrzeug lädt"),
		numState(WALLBOX_EV_FOUNDATION_STATES.chargePowerW, "Reale Ladeleistung", "W"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evccMode, "Aktueller EVCC-Modus"),
		numState(WALLBOX_EV_FOUNDATION_STATES.phasesConfigured, "Konfigurierte Phasen"),
		numState(WALLBOX_EV_FOUNDATION_STATES.phasesActive, "Aktive Phasen"),
		numState(WALLBOX_EV_FOUNDATION_STATES.vehicleSocPct, "Fahrzeug-SOC", "%"),
		strState(WALLBOX_EV_FOUNDATION_STATES.vehicleSocQuality, "Fahrzeug-SOC Qualität"),
		strState(WALLBOX_EV_FOUNDATION_STATES.capabilitiesJson, "EV Capabilities (JSON)", "json"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.externalControlConfigured, "Externe Steuerung konfiguriert"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.externalControlActive, "Externe Steuerung aktiv"),
		strState(WALLBOX_EV_FOUNDATION_STATES.externalControlType, "Externer Steuerungstyp"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.gridRewardsActive, "Grid Rewards aktiv"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.smartChargingActive, "Smart Charging aktiv"),
		strState(WALLBOX_EV_FOUNDATION_STATES.externalSourceQuality, "Externe Quellenqualität"),
		strState(WALLBOX_EV_FOUNDATION_STATES.externalSourceUpdatedAt, "Externe Quelle zuletzt", "date"),
		boolState(
			WALLBOX_EV_FOUNDATION_STATES.externalSmartPlanMappingConfigured,
			"Smart-Plan-Mapping konfiguriert",
		),
		boolState(WALLBOX_EV_FOUNDATION_STATES.externalSmartPlanParseable, "Smart-Plan parsebar"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.externalSmartPlanAvailable, "Externer Smart-Plan verfügbar"),
		numState(WALLBOX_EV_FOUNDATION_STATES.externalSmartPlanSlotCount, "Smart-Plan gültige Slots"),
		strState(WALLBOX_EV_FOUNDATION_STATES.externalSmartPlanNextStart, "Nächster Smart-Plan-Start", "date"),
		strState(WALLBOX_EV_FOUNDATION_STATES.externalSmartPlanLastEnd, "Letztes Smart-Plan-Ende", "date"),
		numState(
			WALLBOX_EV_FOUNDATION_STATES.externalPlanRemainingEnergyKwh,
			"Verbleibende externe Planenergie",
			"kWh",
		),
		numState(WALLBOX_EV_FOUNDATION_STATES.externalPlanRemainingMinutes, "Verbleibende Planminuten", "min"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.externalPlanDeadlineUsed, "Departure-Deadline angewandt"),
		strState(WALLBOX_EV_FOUNDATION_STATES.externalSmartPlanJson, "Smart-Plan Slots (JSON)", "json"),
		strState(WALLBOX_EV_FOUNDATION_STATES.externalRawDiagnosticsJson, "Externe Rohdiagnose (JSON)", "json"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.departureMinSocConfigured, "Mindest-SOC zur Abfahrt konfiguriert"),
		numState(WALLBOX_EV_FOUNDATION_STATES.externalMinSocPct, "Externer Smart-Charging-Mindest-SOC", "%"),
		strState(WALLBOX_EV_FOUNDATION_STATES.externalMinSocQuality, "Externer Mindest-SOC Qualität"),
		strState(WALLBOX_EV_FOUNDATION_STATES.vehicleModelSource, "Fahrzeugmodell-Quelle"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.vehicleModelReady, "Fahrzeugmodell bereit"),
		strState(WALLBOX_EV_FOUNDATION_STATES.controlContractModel, "Control-Contract-Modell"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.evccControlContractReady, "EVCC-Control-Contract bereit"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.legacyDirectControlPresent, "Legacy-Direktsteuerung vorhanden"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evccModeControlVariant, "EVCC Mode-Control-Variante"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evccModeFeedbackState, "EVCC Mode-Feedback-State"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.evccModeButtonsReady, "EVCC Mode-Buttons bereit"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.evccModeOffTargetReady, "EVCC control.off gemappt"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.evccModePvTargetReady, "EVCC control.pv gemappt"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.evccModeMinTargetReady, "EVCC control.min gemappt"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.evccModeNowTargetReady, "EVCC control.now gemappt"),
		strState(WALLBOX_EV_FOUNDATION_STATES.preparedEvState, "Vorbereiteter EV-Zustand"),
		strState(WALLBOX_EV_FOUNDATION_STATES.takeoverReason, "Takeover-Grund (vorbereitet)"),
		strState(WALLBOX_EV_FOUNDATION_STATES.externalAuthorityState, "Externe Ladehoheit"),
		numState(WALLBOX_EV_FOUNDATION_STATES.energyToTargetKwh, "Energie bis Ziel-SOC", "kWh"),
		numState(
			WALLBOX_EV_FOUNDATION_STATES.energyToDepartureMinimumKwh,
			"Energie bis Abfahrts-Mindest-SOC",
			"kWh",
		),
		numState(WALLBOX_EV_FOUNDATION_STATES.requiredChargingMinutes, "Erforderliche Ladezeit", "min"),
		strState(WALLBOX_EV_FOUNDATION_STATES.latestRequiredStart, "Spätester erforderlicher Start", "date"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.deadlineRisk, "Deadline-Risiko"),
		numState(
			WALLBOX_EV_FOUNDATION_STATES.externalPlanExpectedSocGainPct,
			"Erwarteter SOC-Gewinn durch externen Plan",
			"%",
		),
		numState(
			WALLBOX_EV_FOUNDATION_STATES.externalPlanExpectedFinalSocPct,
			"Erwarteter End-SOC durch externen Plan",
			"%",
		),
		boolState(WALLBOX_EV_FOUNDATION_STATES.externalPlanCoversTarget, "Externer Plan deckt Ziel-SOC"),
		boolState(
			WALLBOX_EV_FOUNDATION_STATES.externalPlanCoversDepartureMinimum,
			"Externer Plan deckt Abfahrts-Minimum",
		),
		numState(WALLBOX_EV_FOUNDATION_STATES.remainingFeasibleEnergyKwh, "Physikalisch noch ladbare Energie", "kWh"),
		numState(WALLBOX_EV_FOUNDATION_STATES.remainingCheapEnergyKwh, "Energie in günstigen Restfenstern", "kWh"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.economicWindowLossRisk, "Risiko verlorener günstiger Fenster"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.takeoverRecommended, "EMS-Takeover empfohlen (Diagnose)"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.takeoverRequired, "EMS-Takeover erforderlich (Diagnose)"),
		strState(WALLBOX_EV_FOUNDATION_STATES.takeoverSeverity, "Takeover-Schwere (Diagnose)"),
		strState(WALLBOX_EV_FOUNDATION_STATES.recommendedEvState, "Empfohlener EV-Zustand (Diagnose)"),
		strState(WALLBOX_EV_FOUNDATION_STATES.takeoverDecisionJson, "Takeover-Entscheidung (JSON)", "json"),
		strState(WALLBOX_EV_FOUNDATION_STATES.dataQuality, "EV-Datenqualität"),
		strState(WALLBOX_EV_FOUNDATION_STATES.modelJson, "EV-Datenmodell V1 (JSON)", "json"),
		strState(WALLBOX_EV_FOUNDATION_STATES.updatedAt, "EV-Fundament zuletzt gelesen", "date"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.evPlannerParticipating, "EV-Planner nimmt teil"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evPlannerRole, "EV-Planner-Rolle"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evManagementMode, "EV-Management-Modus"),
		numState(WALLBOX_EV_FOUNDATION_STATES.evHardEnergyKwh, "EV Hard-Energie", "kWh"),
		numState(WALLBOX_EV_FOUNDATION_STATES.evTargetEnergyKwh, "EV Ziel-Energie", "kWh"),
		numState(WALLBOX_EV_FOUNDATION_STATES.evAcEnergyRequiredKwh, "EV AC-Bedarf", "kWh"),
		numState(WALLBOX_EV_FOUNDATION_STATES.evPlannedEnergyKwh, "EV geplante Energie", "kWh"),
		numState(WALLBOX_EV_FOUNDATION_STATES.evUnplannedEnergyKwh, "EV ungeplante Energie", "kWh"),
		numState(WALLBOX_EV_FOUNDATION_STATES.evPlannedCostEur, "EV geplante Kosten", "EUR"),
		numState(WALLBOX_EV_FOUNDATION_STATES.evPlannedPvEnergyKwh, "EV geplante PV-Energie", "kWh"),
		numState(WALLBOX_EV_FOUNDATION_STATES.evPlannedGridEnergyKwh, "EV geplante Netzenergie", "kWh"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evPlannedFirstStart, "EV geplanter Start", "date"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evPlannedLastEnd, "EV geplantes Ende", "date"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evPlanQuality, "EV-Planqualität"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evPlanJson, "EV-Plan (JSON)", "json"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.evExecutionEnabled, "EV-Execution Feature-Gate"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionAuthority, "EV-Execution-Hoheit"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.evExecutionReady, "EV-Execution bereit"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionBlockReason, "EV-Execution Sperrgrund"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionDesiredMode, "EV-Execution Desired-Modus"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionDesiredReason, "EV-Execution Desired-Grund"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionActualMode, "EV-Execution Ist-Modus"),
		boolState(WALLBOX_EV_FOUNDATION_STATES.evExecutionSourceFresh, "EVCC-Quelle frisch"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionOwnership, "EV-Execution Ownership"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionOwnedMode, "EV-Execution besessener Modus"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionOwnedSince, "EV-Execution Ownership seit", "date"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionReleaseReason, "EV-Execution Release-Grund"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionPendingMode, "EV-Execution Pending-Modus"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionPendingSince, "EV-Execution Pending seit", "date"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionLastCommand, "EV-Execution letzter Befehl"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionLastCommandAt, "EV-Execution letzter Befehl um", "date"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionLastFeedbackAt, "EV-Execution letztes Feedback um", "date"),
		numState(WALLBOX_EV_FOUNDATION_STATES.evExecutionRetryCount, "EV-Execution Retry-Zähler"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionLastResult, "EV-Execution letztes Ergebnis"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionFailsafeReason, "EV-Execution Fail-Safe"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionPhase, "EV-Execution Phase"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionExplain, "EV-Execution Explain"),
		boolState(
			WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestArmed,
			"EV Phase-5B Live-Test armed (One-Shot)",
			true,
			"switch",
		),
		boolState(
			WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestDisarm,
			"EV Phase-5B Live-Test abbrechen",
			true,
			"button",
		),
		boolState(WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestConsumed, "EV Phase-5B Live-Test verbraucht"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestArmedAt, "EV Phase-5B Live-Test armed um", "date"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestConsumedAt, "EV Phase-5B Live-Test verbraucht um", "date"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestCommand, "EV Phase-5B Live-Test Command"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestResult, "EV Phase-5B Live-Test Ergebnis"),
		strState(WALLBOX_EV_FOUNDATION_STATES.evExecutionLiveTestBlockReason, "EV Phase-5B Live-Test Sperrgrund"),
	].filter((d) => WALLBOX_EV_FOUNDATION_PUBLIC_STATE_IDS.has(d.id)));
}
