/**
 * Reale, individuelle Default-Werte je Klima-Innengerät (1..5) — extrahiert aus der
 * bisherigen admin/jsonConfig.json. Alles, was hier NICHT auftaucht, ist für alle
 * Geräte identisch und steckt direkt im Template (climate_unit_shape.ts).
 *
 * Neu erzeugen: npm run admin-config:generate
 */
export type ClimateUnitOverrides = Record<string, unknown>;

export const CLIMATE_UNIT_DEFAULTS: Record<string, ClimateUnitOverrides> = {
 "1": {
  "enabled": false,
  "name": "Wohnzimmer EG",
  "active_until": "20:00",
  "hard_off_at": "20:00",
  "shared_power_group_id": "outdoor_1",
  "estimated_power_w": 800,
  "on_temp_c": 25.5,
  "off_temp_c": 24,
  "cleaning_duration_min": 35,
  "room_temp_target": "alias.0.Wohnzimmer_EG.Sensoren.Temp_Feucht.Temperatur",
  "room_humidity_enabled": true,
  "room_humidity_target": "alias.0.Wohnzimmer_EG.Sensoren.Temp_Feucht.Luftfeuchtigkeit",
  "feedback_switch_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.status.switch.switch.value",
  "feedback_mode_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.status.airConditionerMode.airConditionerMode.value",
  "cmd_switch_on_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.capabilities.switch-on",
  "cmd_switch_off_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.capabilities.switch-off",
  "cmd_set_mode_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.capabilities.airConditionerMode-setAirConditionerMode",
  "cmd_set_fan_mode_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.capabilities.airConditionerFanMode-setFanMode",
  "cmd_set_cool_setpoint_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.capabilities.thermostatCoolingSetpoint-setCoolingSetpoint",
  "cmd_cleaning_start_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.capabilities.custom.autoCleaningMode-setAutoCleaningMode",
  "feedback_cleaning_state_enabled": true,
  "feedback_cleaning_state_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.status.custom.autoCleaningMode.operatingState.value",
  "feedback_cleaning_mode_enabled": true,
  "feedback_cleaning_mode_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.status.custom.autoCleaningMode.autoCleaningMode.value",
  "feedback_cleaning_progress_enabled": true,
  "feedback_cleaning_progress_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.status.custom.autoCleaningMode.progress.value",
  "cmd_refresh_target": "smartthings.0.40472197-070b-26fc-f422-69cdd84d6aa8.capabilities.refresh-refresh"
 },
 "2": {
  "enabled": true,
  "name": "Josef Zimmer OG",
  "active_until": "19:00",
  "hard_off_at": "19:00",
  "shared_power_group_id": "outdoor_1",
  "estimated_power_w": 650,
  "on_temp_c": 24.5,
  "off_temp_c": 23,
  "cleaning_duration_min": 45,
  "room_temp_target": "alias.0.Josef_Zimmer_OG.Sensoren.Temp_Feucht.Temperatur",
  "room_humidity_enabled": true,
  "room_humidity_target": "alias.0.Josef_Zimmer_OG.Sensoren.Temp_Feucht.Luftfeuchtigkeit",
  "feedback_switch_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.status.switch.switch.value",
  "feedback_mode_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.status.airConditionerMode.airConditionerMode.value",
  "cmd_switch_on_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.capabilities.switch-on",
  "cmd_switch_off_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.capabilities.switch-off",
  "cmd_set_mode_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.capabilities.airConditionerMode-setAirConditionerMode",
  "cmd_set_fan_mode_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.capabilities.airConditionerFanMode-setFanMode",
  "cmd_set_cool_setpoint_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.capabilities.thermostatCoolingSetpoint-setCoolingSetpoint",
  "cmd_cleaning_start_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.capabilities.custom.autoCleaningMode-setAutoCleaningMode",
  "feedback_cleaning_state_enabled": true,
  "feedback_cleaning_state_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.status.custom.autoCleaningMode.operatingState.value",
  "feedback_cleaning_mode_enabled": true,
  "feedback_cleaning_mode_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.status.custom.autoCleaningMode.autoCleaningMode.value",
  "feedback_cleaning_progress_enabled": true,
  "feedback_cleaning_progress_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.status.custom.autoCleaningMode.progress.value",
  "cmd_refresh_target": "smartthings.0.e03855e7-4dc4-bad7-c8c8-1b7dd0293381.capabilities.refresh-refresh"
 },
 "3": {
  "enabled": false,
  "name": "",
  "active_until": "19:00",
  "hard_off_at": "19:00",
  "shared_power_group_id": "",
  "estimated_power_w": 700,
  "on_temp_c": 26,
  "off_temp_c": 24,
  "cleaning_duration_min": 45,
  "room_temp_target": null,
  "room_humidity_enabled": false,
  "room_humidity_target": null,
  "feedback_switch_target": null,
  "feedback_mode_target": null,
  "cmd_switch_on_target": null,
  "cmd_switch_off_target": null,
  "cmd_set_mode_target": null,
  "cmd_set_fan_mode_target": null,
  "cmd_set_cool_setpoint_target": null,
  "cmd_cleaning_start_target": null,
  "feedback_cleaning_state_enabled": false,
  "feedback_cleaning_state_target": "",
  "feedback_cleaning_mode_enabled": false,
  "feedback_cleaning_mode_target": "",
  "feedback_cleaning_progress_enabled": false,
  "feedback_cleaning_progress_target": "",
  "cmd_refresh_target": null
 },
 "4": {
  "enabled": false,
  "name": "",
  "active_until": "19:00",
  "hard_off_at": "19:00",
  "shared_power_group_id": "",
  "estimated_power_w": 700,
  "on_temp_c": 26,
  "off_temp_c": 24,
  "cleaning_duration_min": 45,
  "room_temp_target": null,
  "room_humidity_enabled": false,
  "room_humidity_target": null,
  "feedback_switch_target": null,
  "feedback_mode_target": null,
  "cmd_switch_on_target": null,
  "cmd_switch_off_target": null,
  "cmd_set_mode_target": null,
  "cmd_set_fan_mode_target": null,
  "cmd_set_cool_setpoint_target": null,
  "cmd_cleaning_start_target": null,
  "feedback_cleaning_state_enabled": false,
  "feedback_cleaning_state_target": "",
  "feedback_cleaning_mode_enabled": false,
  "feedback_cleaning_mode_target": "",
  "feedback_cleaning_progress_enabled": false,
  "feedback_cleaning_progress_target": "",
  "cmd_refresh_target": null
 },
 "5": {
  "enabled": false,
  "name": "",
  "active_until": "19:00",
  "hard_off_at": "19:00",
  "shared_power_group_id": "",
  "estimated_power_w": 700,
  "on_temp_c": 26,
  "off_temp_c": 24,
  "cleaning_duration_min": 45,
  "room_temp_target": null,
  "room_humidity_enabled": false,
  "room_humidity_target": null,
  "feedback_switch_target": null,
  "feedback_mode_target": null,
  "cmd_switch_on_target": null,
  "cmd_switch_off_target": null,
  "cmd_set_mode_target": null,
  "cmd_set_fan_mode_target": null,
  "cmd_set_cool_setpoint_target": null,
  "cmd_cleaning_start_target": null,
  "feedback_cleaning_state_enabled": false,
  "feedback_cleaning_state_target": "",
  "feedback_cleaning_mode_enabled": false,
  "feedback_cleaning_mode_target": "",
  "feedback_cleaning_progress_enabled": false,
  "feedback_cleaning_progress_target": "",
  "cmd_refresh_target": null
 }
};
